// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Varejao.Data;

#nullable disable

namespace Varejao.Migrations
{
    [DbContext(typeof(VarejaoContext))]
    partial class VarejaoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Varejao.Model.Hortifruti", b =>
                {
                    b.Property<int>("IdHortifruti")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHortifruti"));

                    b.Property<float>("Cofins")
                        .HasColumnType("real");

                    b.Property<int>("EstoqueAtual")
                        .HasColumnType("int");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("int");

                    b.Property<float>("Icms")
                        .HasColumnType("real");

                    b.Property<float>("Iss")
                        .HasColumnType("real");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PrecoCusto")
                        .HasColumnType("real");

                    b.Property<float>("PrecoVenda")
                        .HasColumnType("real");

                    b.HasKey("IdHortifruti");

                    b.ToTable("Hortifruti");
                });

            modelBuilder.Entity("Varejao.Model.Lote", b =>
                {
                    b.Property<int>("IdLote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLote"));

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fornecedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdHortifruti")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeHortifruti")
                        .HasColumnType("int");

                    b.HasKey("IdLote");

                    b.HasIndex("IdHortifruti");

                    b.ToTable("Lote");
                });

            modelBuilder.Entity("Varejao.Model.Lote", b =>
                {
                    b.HasOne("Varejao.Model.Hortifruti", "Hortifruti")
                        .WithMany("Lotes")
                        .HasForeignKey("IdHortifruti")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hortifruti");
                });

            modelBuilder.Entity("Varejao.Model.Hortifruti", b =>
                {
                    b.Navigation("Lotes");
                });
#pragma warning restore 612, 618
        }
    }
}
